###
GET http://localhost:3000/api/vuelos/2007

####
POST http://localhost:3000/api/vuelos
Content-Type: application/json

{
    "Year": "1987",
    "Month": "100",
    "DayofMonth": "14",
    "DayOfWeek": "2"
}

###
GET http://localhost:3000/api/vuelos/limit/2000/
Content-Type: application/json

{
    "Month": "1",
    "DayofMonth": "1",
    "DayOfWeek": "1"
}





###
PUT http://localhost:3000/api/vuelos/1987/5fbfd21c553fb20fec7baa4f
Content-Type: application/json

{
    "Month": "12"
    
}



###
DELETE  http://localhost:3000/api/vuelos/1987/5fbfd21c553fb20fec7baa4f



