###
GET http://localhost:3000/api/vuelos

####
POST http://localhost:3000/api/vuelos
Content-Type: application/json

{
    "Year": "1987",
    "Month": "01",
    "DayofMonth": "14",
    "DayOfWeek": "2"
}

###
GET http://localhost:3000/api/vuelos/limit/1987/
Content-Type: application/json

{
    "Month": "12", 
    "_id": "5fbc29171a1d354f3c7423aa"
    
}





###
PUT http://localhost:3000/api/vuelos/1987/5fbc29171a1d354f3c7423aa
Content-Type: application/json

{
    "Month": "12"
    
}



###
DELETE  http://localhost:3000/api/vuelos/1987/5fbc29171a1d354f3c7423aa



